// Generated by https://quicktype.io

export interface FavoritesPaginatedResp {
    status: string;
    data:   Datum[];
}

export interface Datum {
    id_receta:          number;
    titulo:             string;
    nombre:             string;
    tiempo_preparacion: number;
    puntaje:            null;
    imagen:             string;
}


export interface Tag {
    id: number;
    descripcion: string;
}