// Generated by https://quicktype.io

export interface MisRecetasPaginatedResp {
    status: string;
    data:   Datum[];
}

export interface Datum {
    id_receta:          number;
    titulo:             string;
    nombre:             string;
    tiempo_preparacion: number;
    puntaje:            null;
    imagen:             string;
}
