// Generated by https://quicktype.io

export interface RecipesPaginatedResp {
    status: string;
    data:   Datum[];
}

export interface Datum {
    id_receta:          number;
    titulo:             string;
    nombre:             string;
    tiempo_preparacion: number;
    puntaje:            string;
    imagen:             string;
}

export interface SimpleRecipe {
    id_receta:          number;
    titulo:             string;
    nombre:             string;
    puntaje:            string;
    imagen:             string;
}
